name: Run Renovate to update base-images

on:
  schedule:
    # daily at 02:00 UTC — change as needed
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate Action
        # The correct path is renovatebot/renovate-action
        uses: renovatebot/renovate-action@v40
        with:
          # Your config file path, relative to the repository root
          config-file: .github/renovate.json

          # The token is passed as an input, not an env var
          token: ${{ secrets.GITHUB_TOKEN }}
        
        # Pass registry credentials as env vars
        # The Renovate process will automatically detect and use them
        env:
          DOCK"OCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
