name: Run Renovate (Docker) to update base-images

on:
  schedule:
    # daily at 02:00 UTC — change as needed
    - cron: '0 2 * * *'
  workflow_dispatch: {}

# Add 'issues: write' here
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Docker is available
        run: docker --version

      - name: Run Renovate (Docker)
        env:
          # token used by Renovate to create PRs
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # optional Docker Hub auth to avoid rate limits
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # set config file path inside the container
          RENOVATE_CONFIG_FILE: /usr/src/app/.github/renovate.json
        run: |
          # run the official Renovate Docker image against the checked-out repo
          docker run --rm \
            -v "${{ github.workspace }}:/usr/src/app" \
            -e RENOVATE_TOKEN \
            -e DOCKER_HUB_USERNAME \
            -e DOCKER_HUB_PASSWORD \
            -e RENOVATE_CONFIG_FILE \
            renovate/renovate:latest \
            ${{ github.repository }} \
            --platform=github
